# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


variables:
- group: New variable group 06-Jul

trigger:
- master

pool:
  vmImage: ubuntu-latest

schedules:
- cron: "0 0 * * *"
  displayName: "Daily build"
  branches:
    include:
    - master

jobs:
  - job: Run_Credential_Scan_Daily_Job 
    displayName: Run_Credential_Scan_Daily
    timeoutInMinutes: 360
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      clean: false
    - script: echo Hello, world!
    
    - task: CredScan@3
      displayName: Run Credential Scanner
      inputs:
        debugMode: false
        folderSuppression: false
    - task: PublishSecurityAnalysisLogs@3
      displayName: Publish Guardian Artifacts
      
    
